sonar.projectKey=sia-rdelgemini
sonar.projectName=SIA - Course Registration Platform

sonar.sources=backend
sonar.exclusions=backend/__tests__/**, node_modules/**

sonar.tests=backend/__tests__

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectVersion=1.0
